name: Build and Upload ISO to Vultr

on:
  workflow_dispatch:

env:
  RR_VERSION: "25.6.5"
  DOWNLOAD_URL: "https://github.com/RROrg/rr/releases/download/25.6.5/rr-25.6.5.img.zip"
  ZIP_FILE: "rr-25.6.5.img.zip"
  ISO_FILE: "rr-25.6.5.iso"
  # 重要：在这里填入你的 Vultr 存储桶名称
  VULTR_BUCKET_NAME: "your-bucket-name" 

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: 检出仓库代码 (Checkout repository)
        uses: actions/checkout@v4

      - name: 安装依赖工具 (Install dependencies)
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-utils unzip s3cmd

      - name: 下载 Release 压缩包 (Download release package)
        run: wget ${{ env.DOWNLOAD_URL }}

      - name: 解压文件 (Unzip the package)
        run: unzip ${{ env.ZIP_FILE }}

      - name: 转换 IMG 为 ISO (Convert IMG to ISO)
        run: |
          IMG_FILE_PATH=$(find . -type f -name "*.img" | head -n 1)
          if [ -z "$IMG_FILE_PATH" ]; then
            echo "错误：解压后未在任何位置找到 .img 文件！"
            exit 1
          fi
          echo "成功找到 IMG 文件: $IMG_FILE_PATH"
          qemu-img convert -f raw "$IMG_FILE_PATH" "${{ env.ISO_FILE }}"
          echo "转换完成。"

      # 新增！最后一步：上传到 Vultr 对象存储
      - name: 上传文件到 Vultr S3 (Upload to Vultr S3)
        env:
          VULTR_ACCESS_KEY: ${{ secrets.VULTR_ACCESS_KEY }}
          VULTR_SECRET_KEY: ${{ secrets.VULTR_SECRET_KEY }}
        run: |
          echo "正在配置 s3cmd..."
          # 动态创建 s3cmd 配置文件，使用你提供的 Vultr 主机信息
          cat > ~/.s3cfg <<EOF
          [default]
          access_key = ${VULTR_ACCESS_KEY}
          secret_key = ${VULTR_SECRET_KEY}
          host_base = ams1.vultrobjects.com
          host_bucket = test111.ams1.vultrobjects.com
          use_https = True
          EOF

          echo "正在上传文件..."
          # -P 参数使文件公开可读
          s3cmd put --acl-public --recursive ${{ env.ISO_FILE }} s3://${{ env.VULTR_BUCKET_NAME }}/

          echo "上传成功！文件已上传至 s3://${{ env.VULTR_BUCKET_NAME }}/"
